export class ItemWeight {
	public id: number;
	public des: string;
	public name: string;
	public weight: number;
	public star: number;
}
export class ItemWeightMap {
	public data: Map<number, ItemWeight> = new Map<number, ItemWeight>()
	constructor() {
		let tempData: ItemWeight;
		tempData = new ItemWeight;
		tempData.id = 0;
		tempData.des = "书包";
		tempData.name = "dmm_bag_01";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 1;
		tempData.des = "盒子（绿）";
		tempData.name = "dmm_basket_01";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 2;
		tempData.des = "盒子（粉）";
		tempData.name = "dmm_basket_02";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 3;
		tempData.des = "篮球";
		tempData.name = "dmm_basketball_01";
		tempData.weight = 30;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 4;
		tempData.des = "烧瓶";
		tempData.name = "dmm_beaker_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 6;
		tempData.des = "书（绿）";
		tempData.name = "dmm_book_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 7;
		tempData.des = "水果箱";
		tempData.name = "dmm_box_01";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 8;
		tempData.des = "凳子（黄）";
		tempData.name = "dmm_chair_01";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 9;
		tempData.des = "凳子（绿）";
		tempData.name = "dmm_chair_02";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 10;
		tempData.des = "原凳";
		tempData.name = "dmm_chair_03";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 12;
		tempData.des = "试管架";
		tempData.name = "dmm_cylinder_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 13;
		tempData.des = "教室桌子";
		tempData.name = "dmm_desk_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 14;
		tempData.des = "头枕";
		tempData.name = "dmm_dillow_01";
		tempData.weight = 200;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 16;
		tempData.des = "灭火器";
		tempData.name = "dmm_fireextinguisher_01";
		tempData.weight = 100;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 17;
		tempData.des = "switch";
		tempData.name = "dmm_game_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 18;
		tempData.des = "地球仪";
		tempData.name = "dmm_globe_01";
		tempData.weight = 400;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 19;
		tempData.des = "消防箱";
		tempData.name = "dmm_hydrantbox_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 20;
		tempData.des = "讲台";
		tempData.name = "dmm_lecturedesk_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 22;
		tempData.des = "饭店牌子";
		tempData.name = "dmm_menuboard_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 23;
		tempData.des = "显微镜";
		tempData.name = "dmm_microscope_01";
		tempData.weight = 200;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 26;
		tempData.des = "笔记本电脑";
		tempData.name = "dmm_notebook_01";
		tempData.weight = 200;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 28;
		tempData.des = "大叶子花盆";
		tempData.name = "dmm_pot_02";
		tempData.weight = 400;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 29;
		tempData.des = "仙人掌";
		tempData.name = "dmm_pot_03";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 30;
		tempData.des = "垃圾桶（蓝）";
		tempData.name = "dmm_recyclebin_01";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 31;
		tempData.des = "垃圾桶（黄）";
		tempData.name = "dmm_recyclebin_02";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 32;
		tempData.des = "化学柜";
		tempData.name = "dmm_scale_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 33;
		tempData.des = "骷髅";
		tempData.name = "dmm_skeleton_01";
		tempData.weight = 400;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 34;
		tempData.des = "足球";
		tempData.name = "dmm_soccerball_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 36;
		tempData.des = "小垃圾桶（灰色）";
		tempData.name = "dmm_trashcan_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 38;
		tempData.des = "伞桶";
		tempData.name = "dmm_umbrellastand_01";
		tempData.weight = 200;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 40;
		tempData.des = "热水机";
		tempData.name = "dmm_waterheater_01";
		tempData.weight = 200;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 41;
		tempData.des = "饮水机";
		tempData.name = "dmm_waterpurifier_01";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 27;
		tempData.des = "芦荟花盆";
		tempData.name = "dmm_pot_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 42;
		tempData.des = "书（蓝色）";
		tempData.name = "dmm_book_02";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 43;
		tempData.des = "书（白色）";
		tempData.name = "dmm_book_03";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 44;
		tempData.des = "透明盒子";
		tempData.name = "dmm_box_02";
		tempData.weight = 300;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 45;
		tempData.des = "咖啡杯";
		tempData.name = "dmm_tumbler_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 46;
		tempData.des = "镜子（1）";
		tempData.name = "dmm_mirror_01";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 47;
		tempData.des = "镜子（2）";
		tempData.name = "dmm_mirror_02";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 48;
		tempData.des = "橄榄球";
		tempData.name = "dmm_rugby_01";
		tempData.weight = 30;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 49;
		tempData.des = "调味盒";
		tempData.name = "dmm_salt_01";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 50;
		tempData.des = "雨伞";
		tempData.name = "dmm_umbrella_01";
		tempData.weight = 100;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 51;
		tempData.des = "菜篮子";
		tempData.name = "dmm_basket_01";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 52;
		tempData.des = "小熊";
		tempData.name = "dmm_bear";
		tempData.weight = 500;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 53;
		tempData.des = "头枕（粉色）";
		tempData.name = "dmm_dillow_02";
		tempData.weight = 200;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 54;
		tempData.des = "拖鞋";
		tempData.name = "dmm_slipper_01";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 55;
		tempData.des = "盘子（1）";
		tempData.name = "dmm_dish_01";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 56;
		tempData.des = "盘子（2）";
		tempData.name = "dmm_dish_02";
		tempData.weight = 10;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 57;
		tempData.des = "盘子（3）";
		tempData.name = "dmm_dish_03";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 58;
		tempData.des = "盘子（4）";
		tempData.name = "dmm_dish_04";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 59;
		tempData.des = "盘子（5）";
		tempData.name = "dmm_dish_05";
		tempData.weight = 0;
		tempData.star = 0;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 0;
		tempData.des = "书包";
		tempData.name = "dmm_bag_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 1;
		tempData.des = "盒子（绿）";
		tempData.name = "dmm_basket_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 2;
		tempData.des = "盒子（粉）";
		tempData.name = "dmm_basket_02";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 3;
		tempData.des = "篮球";
		tempData.name = "dmm_basketball_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 4;
		tempData.des = "烧瓶";
		tempData.name = "dmm_beaker_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 6;
		tempData.des = "书（绿）";
		tempData.name = "dmm_book_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 7;
		tempData.des = "水果箱";
		tempData.name = "dmm_box_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 12;
		tempData.des = "试管架";
		tempData.name = "dmm_cylinder_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 14;
		tempData.des = "头枕";
		tempData.name = "dmm_dillow_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 16;
		tempData.des = "灭火器";
		tempData.name = "dmm_fireextinguisher_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 17;
		tempData.des = "switch";
		tempData.name = "dmm_game_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 19;
		tempData.des = "消防箱";
		tempData.name = "dmm_hydrantbox_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 26;
		tempData.des = "笔记本电脑";
		tempData.name = "dmm_notebook_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 29;
		tempData.des = "仙人掌";
		tempData.name = "dmm_pot_03";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 34;
		tempData.des = "足球";
		tempData.name = "dmm_soccerball_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 38;
		tempData.des = "伞桶";
		tempData.name = "dmm_umbrellastand_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 45;
		tempData.des = "咖啡杯";
		tempData.name = "dmm_tumbler_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 48;
		tempData.des = "橄榄球";
		tempData.name = "dmm_rugby_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
		tempData = new ItemWeight;
		tempData.id = 54;
		tempData.des = "拖鞋";
		tempData.name = "dmm_slipper_01";
		tempData.weight = 100;
		tempData.star = 30;
		this.data.set(tempData.id, tempData);
	}
}
